### ISSUE TITLE
Locator field

### ISSUE THREAD

**Issue by niranjan8129** [anujkumar21/PWAF#5]
Hi, I appreciated and liked your  code. Just have one concern. how to find out locator ?

**Comment by anujkumar21** [comment]
Hi Niranjan,

Sorry for the delay in reply. 

Have you worked on web or mobile automation projects? If yes, the way to find locators is same. If not, you can find the locators using developer options of browser or you can use different plugins which come as browser extensions.
Here is a good link for reference:
https://www.softwaretestinghelp.com/using-selenium-xpath-and-other-locators-selenium-tutorial-5/

Please feel free to reach in case of any queries.

Thanks,
Anuj
