### ISSUE TITLE
Ask for contribution

### ISSUE THREAD

**Issue by yipeitu** [anujkumar21/PWAF#6]
Hi Anuj,

We're two students, Kartik and Yi-Pei, from KTH Royal Institute, Sweden.
We're taking a course about Dev-Ops (https://github.com/KTH/devops-course).
We found your open project, PWAF, is quite interesting for us.
We also notice that there are something left in the plan.
May we continue your work and try to complete it?
Thanks.

**Comment by anujkumar21** [comment]
Hi Yi-Pei & Kartik,

Thanks for reaching out.
I am glad to know that my work is of interest and use for your learning.
Contributions are welcome :)

Feel free to reach out in case of any queries.

Thanks,
Anuj

**Comment by yipeitu** [comment]
Hi Anuj,

Thanks :)
We're working on it but we faced a problem that it shows an error to executre 'nosetests -s -v --nologcapture group=smoke all_tests.py'
The error is 'ValueError: Unable to load tests from file ....../testcases/group=smoke'
Do you have any ideas about it?

**Comment by anujkumar21** [comment]
Ahh @yipeitu my bad I missed -a in the execution command. I have updated the README
Please try with this command.
nosetests -s -v --nologcapture -a group=smoke all_tests.py

**Comment by yipeitu** [comment]
Hi Anuj,

It works now 👍 Thanks.

**Comment by anujkumar21** [comment]
You are welcome.
