### ISSUE TITLE
Questions about Grids

### ISSUE THREAD

**Issue by yipeitu** [anujkumar21/PWAF#7]
Hi Anuj,

We are almost finished "Functionality To Automate."
https://github.com/mudaliarkartik/devops-course/tree/T2_Open/contributions/open/mudaliar-yptu/PWAF
But we're not sure about what does Grids mean in Framework Level.
Could you explain it a bit more?
Thanks.

**Comment by anujkumar21** [comment]
Grid you need to setup separately. and with the help remote WebDriver class you can execute you scripts.

`from selenium import webdriver`

`selenium_grid_url = "http://198.0.0.1:4444/wd/hub"`

`# Create a desired capabilities object as a starting point.`
`capabilities = DesiredCapabilities.FIREFOX.copy()`
`capabilities['platform'] = "WINDOWS"`
`capabilities['version'] = "10"`

`# Instantiate an instance of Remote WebDriver with the desired capabilities.`
`driver = webdriver.Remote(desired_capabilities=capabilities, command_executor=selenium_grid_url)`
