### ISSUE TITLE
Question regarding python version

### ISSUE THREAD

**Issue by MeghaSareen** [anujkumar21/PWAF#8]
Hi Anuj,

I was looking for selenium projects online for contribution and found your project. I find it interesting and would like to contribute. I have couple of questions:
 1. I don't see any contributions since April 2019, Are there any features remaining to test or project is complete? 
 2. Is this project using python 2 and if yes, are you planning to upgrade to python 3?
 
Thanks.

**Comment by anujkumar21** [comment]
Hi Megha,

Thanks for going through my repo.

Its a sample project which I use to teach my students.
Currently this project is in python2.7, which I am not planning to change right now.

Yes there are many things which are in pipeline to enhance this framework. Would appreciate if you want to work on enhancements.

Thanks & Regards,
Anuj Kumar

**Comment by MeghaSareen** [comment]
Happy to get on board with that.

Do you mind me asking do you teach online ? I have started learning
selenium automation with python recently and would be interested in joining
if possible. Can you share more details on what you teach and how to join?

Thanks,
Megha
